### ISSUE TITLE
Spike: Work out how to do routing in elm 

### ISSUE THREAD

**Issue by ZooeyMiller** [ZooeyMiller/rounded-app#12]
Since we're making a single page app with multiple views we need to work out how to route between each page

**Comment by ZooeyMiller** [comment]
At the moment we are using ```Navigation``` and using ```Navigation.newUrl``` which changes the url bar, what we now need to do is work out how to modify our model so that it takes in the new ```Navigation.location```

**Comment by finnhodgkin** [comment]
I heard you just put location= location on the model....
...
...
...
😢

**Comment by ZooeyMiller** [comment]
@finnhodgkin omg. :cry: :cry: :cry:
