### ISSUE TITLE
Output elm-make to a JS file to be pulled into our own HTML file

### ISSUE THREAD

**Issue by ZooeyMiller** [ZooeyMiller/rounded-app#14]
We need to do this so that we can easily link in our own style tags and set the meta tags easily.

**Comment by ZooeyMiller** [comment]
This isn't _automatic_ but we have set up an index.html to which the js is spat into.

I think if we make a npm script that does this we could comfortably close this issue.

**Comment by finnhodgkin** [comment]
This is now automatic using elm-live. Closing :+1:
