### ISSUE TITLE
UI Inspiration?

### ISSUE THREAD

**Issue by nelsonic** [ZooeyMiller/rounded-app#17]
Fairly certain you already know about this and are going to make _much_ more intuitive UI/UX,
but in case you haven't seen Moodnotes see: 
+ Intro video: https://youtu.be/5WeNXZ-BVqA
+ http://moodnotes.thriveport.com (iOS-only)
Interview with the Devs: http://www.androidauthority.com/moodnotes-developer-interview-777821
![image](https://user-images.githubusercontent.com/194400/26850634-2971534c-4b00-11e7-95d2-68daaa0b53ff.png)
![image](https://user-images.githubusercontent.com/194400/26850643-2e921b4a-4b00-11e7-9c60-4afcdbd50b99.png)

**Comment by ZooeyMiller** [comment]
Awesome! Thanks. We're going for a _much_ more minimal look and feel, hopefully it works well, I'm looking forward to taking this to users for some feedback.
