### ISSUE TITLE
Add "graph view" button to setMood page

### ISSUE THREAD

**Issue by ZooeyMiller** [ZooeyMiller/rounded-app#51]
you have to enter a mood to view your graph right now, that's not good.

**Comment by finnhodgkin** [comment]
Should we allow this before three graph inputs have happened? At the moment we have three prompts before the mood selection page moves on to the graph page.

I guess we could grey out the graph button until > 2 emotionDatum inputs.

**Comment by ZooeyMiller** [comment]
@finnhodgkin good point. should only show once they have inputted 3 or more
